# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cea6050eb22e9add4882867fb946713fee1bb78ec9463dbf649a73f7acc9bf9a67e56b8ada129891459d6f38d64ff31ca2630fe3c1c77b78c401f8132c39047

test:
  secret_key_base: eaacf1ede3d0b6254f25cf7fbe5057cf439ce1d5bfaa8233a490d7c28c139a458dde060556bcf40ced3e5463157d971c41299f541164082f3ec2d79b527c4133

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
