#!/usr/bin/env sh
if [ $# -lt 1 ]; then
	echo "./railsnew <project> <--args>"
	exit 1
fi

NAME="$1"
shift
ARGS="$@"

mkdir $NAME
cd $NAME
echo -e "source 'https://rubygems.org'\ngem 'rails'\n" > Gemfile
bundix -l
cp ../panel/.envrc .
cp ../panel/shell.nix .
nix-shell --run "rails plugin new . --force --skip-bundle $ARGS"
bundix -l
rm -rf .git
